# Çoklu Doğrusal Regresyon

In [3]:
import pandas as pd
df = pd.read_csv("Advertising.csv")
df = df.iloc[:, 1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X = df.drop('sales', axis=1)
y = df[["sales"]]

In [5]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [6]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [7]:
#Statsmodels
import statsmodels.api as sm

In [8]:
lm = sm.OLS(y, X)

In [9]:
model = lm.fit()

In [10]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.982
Model:                            OLS   Adj. R-squared:                  0.982
Method:                 Least Squares   F-statistic:                     3566.
Date:                Sat, 19 Dec 2020   Prob (F-statistic):          2.43e-171
Time:                        17:01:08   Log-Likelihood:                -423.54
No. Observations:                 200   AIC:                             853.1
Df Residuals:                     197   BIC:                             863.0
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [11]:
# scikit learn
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
model = lm.fit(X, y)

In [12]:
model.intercept_

array([2.93888937])

In [13]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

### Prediction

##### Sales = 2.94 + TV*0.04 + radio * 0.19 - newspaper * 0.001

In [14]:
new_data = [[30], [10], [40]]

In [15]:
new_data = pd.DataFrame(new_data).T # transpose
new_data.columns= ("tv", "radio", "newspaper")

In [16]:
new_data

tv  radio  newspaper
0  30     10         40

In [17]:
model.predict(new_data)

array([[6.15562918]])

In [18]:
# MSE
from sklearn.metrics import mean_squared_error

In [19]:
MSE = mean_squared_error(y, model.predict(X))
MSE

2.784126314510936

In [20]:
# RMSE
import numpy as np
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697

### Model Tuning

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [36]:
lm = LinearRegression()
model = lm.fit(X_train, y_train)

In [37]:
# train error
np.sqrt(mean_squared_error(y_train, model.predict(X_train)))

1.7369025901470923

In [38]:
# test error
np.sqrt(mean_squared_error(y_test, model.predict(X_test)))

1.4113417558581578

In [39]:
# k fold cross validation
from sklearn.model_selection import cross_val_score

In [42]:
# cv MSE
np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring='neg_mean_squared_error'))

3.1877115209443576

In [43]:
# cv RMSE
np.sqrt(np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring='neg_mean_squared_error')))

1.7854163438661463